project:
  type: website
  output-dir: docs
  
website:
  title: "Katz Performance"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - href: class-projects.qmd
            text: "CMSC 405 Projects"
          - href: ml-projects.qmd
            text: "ML Projects"
          - href: research-projects.qmd
            text: "Formal Research Projects"
      - text: Visualizations
        menu: 
          - href: force-plate.qmd
            text: "Force Plate Analysis"
      - href: about.qmd
        text: About

format:
  html:
    theme: cyborg 
    css: styles.css
    toc: true


