project:
  type: website
  output-dir: docs
  
website:
  title: "Katz Performance"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - href: class-projects.qmd
            text: "CMSC/STAT 405 Work"
          - href: external-projects.qmd
            text: "Baseball Research"
      - href: about.qmd
        text: Interests

format:
  html:
    theme: cyborg 
    css: styles.css
    toc: true


