project:
  type: website
  output-dir: docs
  
website:
  title: "Katz Performance"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - href: class-projects.qmd
            text: "CMSC 405 Projects"
          - href: general-projects.qmd
            text: "Case Studies"
          - href: research-projects.qmd
            text: "Formal Research Projects"
      - href: about.qmd
        text: Bio

format:
  html:
    theme: cyborg 
    css: styles.css
    toc: true


